name: Publish Helm Chart
description: 'Builds and publishes a Helm chart to Helm registry'
inputs:
  chartVersion:
    description: 'The version of the chart to build'
    required: true
    type: string
  repoName:
    description: 'The name of the repository'
    required: true
    type: string
  dockerRegistryUsername:
    description: 'The username for the helm registry'
    required: false
    type: string
  dockerRegistryAccessToken:
    description: 'The access token for the helm registry'
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - name: Show inputs
      shell: bash
      run: |
        echo "chartVersion: ${{ inputs.chartVersion }}"
        echo "repoName: ${{ inputs.repoName }}"
        echo "dockerRegistryUsername: ${{ inputs.dockerRegistryUsername != '' && 'set' || 'empty' }}"
        echo "dockerRegistryAccessToken: ${{ inputs.dockerRegistryAccessToken != '' && 'set' || 'empty' }}"
    - name: Checkout chart-repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        repository: ${{ inputs.repoName }}
        fetch-depth: 0
    - name: Chart Build and Push
      uses: appany/helm-oci-chart-releaser@v0.5.0
      with:
        path: .
        name: ${{ inputs.repoName }}
        repository: cads/helm
        tag: 0.0.0
        registry: eccr.ecmwf.int
        registry_username: ${{ inputs.dockerRegistryUsername }}
        registry_password: ${{ inputs.dockerRegistryAccessToken }}