name: 'Copy Git Clone Script'
description: 'It copies the git clone script'
inputs:
  target-path:
    description: 'The path where the script should be copied'
    required: true
runs:
  using: "composite"
  steps:
    - name: Copy git clone script to ${{ inputs.target-path }}
      env:
        TARGET_PATH: ${{ inputs.target-path }}
      shell: bash
      run: |
        cp ${{ github.action_path }}/../scripts/git-clone-ref.py ${TARGET_PATH}
